/** @type {import('tailwindcss').Config} */
const withAlpha = (variable) => `rgb(var(${variable}) / <alpha-value>)`

export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: withAlpha('--color-primary-rgb'),
        secondary: withAlpha('--color-secondary-rgb'),
        danger: withAlpha('--color-danger-rgb'),
        success: withAlpha('--color-success-rgb'),
        warning: withAlpha('--color-warning-rgb'),
        info: withAlpha('--color-info-rgb'),
        bg: withAlpha('--color-bg-rgb'),
        surface: withAlpha('--color-surface-rgb'),
        card: withAlpha('--color-card-rgb'),
        border: withAlpha('--color-border-rgb'),
        'text-primary': withAlpha('--color-text-primary-rgb'),
        'text-secondary': withAlpha('--color-text-secondary-rgb'),
        'text-muted': withAlpha('--color-text-muted-rgb'),
        'text-disabled': withAlpha('--color-text-disabled-rgb'),
        'text-inverse': withAlpha('--color-text-inverse-rgb'),
        overlay: withAlpha('--color-overlay-rgb'),
        human: withAlpha('--color-human-rgb'),
        zombie: withAlpha('--color-zombie-rgb'),
        gold: withAlpha('--color-gold-rgb'),
        'game-panel': withAlpha('--color-game-panel-rgb'),
        'game-input': withAlpha('--color-game-input-rgb'),
        'game-title': withAlpha('--color-game-title-rgb'),
        'game-accent': withAlpha('--color-game-accent-rgb'),
        'game-cta-start': withAlpha('--color-game-cta-start-rgb'),
        'game-cta-end': withAlpha('--color-game-cta-end-rgb'),
        'game-cta-border': withAlpha('--color-game-cta-border-rgb'),
        'game-wood-start': withAlpha('--color-game-wood-start-rgb'),
        'game-wood-end': withAlpha('--color-game-wood-end-rgb'),
        'game-border': withAlpha('--color-game-border-rgb'),
        'on-game': withAlpha('--color-on-game-rgb'),
        /* Legacy aliases */
        void: withAlpha('--color-bg-rgb'),
        abyss: withAlpha('--color-surface-rgb'),
        slate: withAlpha('--color-card-rgb'),
        fog: withAlpha('--color-text-primary-rgb'),
        mist: withAlpha('--color-text-secondary-rgb'),
        blood: withAlpha('--color-primary-rgb'),
        plague: withAlpha('--color-success-rgb'),
      },
      spacing: {
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
        '4xl': 'var(--space-4xl)',
      },
      borderRadius: {
        sm: 'var(--radius-small)',
        DEFAULT: 'var(--radius-medium)',
        md: 'var(--radius-medium)',
        lg: 'var(--radius-large)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        '4xl': 'var(--radius-3xl)',
        pill: 'var(--radius-pill)',
        circle: 'var(--radius-circle)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        body: 'var(--font-body)',
      },
      fontSize: {
        caption: ['var(--text-caption-size)', { lineHeight: 'var(--text-caption-leading)', fontWeight: 'var(--text-caption-weight)' }],
        body: ['var(--text-body-size)', { lineHeight: 'var(--text-body-leading)', fontWeight: 'var(--text-body-weight)' }],
        subtitle: ['var(--text-subtitle-size)', { lineHeight: 'var(--text-subtitle-leading)', fontWeight: 'var(--text-subtitle-weight)' }],
        title: ['var(--text-title-size)', { lineHeight: 'var(--text-title-leading)', fontWeight: 'var(--text-title-weight)' }],
        heading: ['var(--text-heading-size)', { lineHeight: 'var(--text-heading-leading)', fontWeight: 'var(--text-heading-weight)' }],
        display: ['var(--text-display-size)', { lineHeight: 'var(--text-display-leading)', fontWeight: 'var(--text-display-weight)' }],
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        card: 'var(--shadow-card)',
        glow: 'var(--shadow-glow)',
        'glow-danger': 'var(--shadow-glow-danger)',
        'glow-success': 'var(--shadow-glow-success)',
        'glow-warning': 'var(--shadow-glow-warning)',
        'glow-primary': 'var(--shadow-glow-primary)',
        /* Legacy */
        'glow-red': 'var(--shadow-glow-danger)',
        'glow-green': 'var(--shadow-glow-success)',
        'glow-gold': 'var(--shadow-glow-warning)',
      },
      zIndex: {
        dropdown: 'var(--z-dropdown)',
        sticky: 'var(--z-sticky)',
        fixed: 'var(--z-fixed)',
        'modal-backdrop': 'var(--z-modal-backdrop)',
        modal: 'var(--z-modal)',
        popover: 'var(--z-popover)',
        toast: 'var(--z-toast)',
        tooltip: 'var(--z-tooltip)',
        max: 'var(--z-max)',
      },
      opacity: {
        disabled: 'var(--opacity-disabled)',
        muted: 'var(--opacity-muted)',
        overlay: 'var(--opacity-overlay)',
        backdrop: 'var(--opacity-backdrop)',
        highlight: 'var(--opacity-highlight)',
        border: 'var(--opacity-border)',
        'border-strong': 'var(--opacity-border-strong)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        DEFAULT: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        DEFAULT: 'var(--ease-default)',
        in: 'var(--ease-in)',
        out: 'var(--ease-out)',
        bounce: 'var(--ease-bounce)',
      },
      maxWidth: {
        mobile: 'var(--layout-mobile-width)',
      },
      minHeight: {
        mobile: 'var(--layout-mobile-height)',
      },
      animation: {
        'ds-pulse': 'ds-pulse var(--duration-slower) var(--ease-default) infinite',
        'ds-float': 'ds-float 3s var(--ease-default) infinite',
        'pulse-glow': 'ds-pulse var(--duration-slower) var(--ease-default) infinite',
        float: 'ds-float 3s var(--ease-default) infinite',
      },
      keyframes: {
        'ds-pulse': {
          '0%, 100%': { opacity: 'var(--opacity-muted)' },
          '50%': { opacity: '1' },
        },
        'ds-float': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(calc(var(--space-sm) * -1.5))' },
        },
      },
    },
  },
  plugins: [],
}
